### ISSUE TITLE
contributing improvements

### ISSUE THREAD

**Issue by redshark1802** [terramar-labs/packages#38]
Hello,

I'd like to contribute some improvements to packages, but I have a big question upfront.

Is there a specific reason not to use symfony all the way?
Would you be happy if I migrate the code to symfony, or should I start a new project and use packages just as a dependency?

The best,
Simon

**Comment by tyler-sommer** [comment]
Hi @redshark1802. It's probably far too late for me to chime in on this, but for posterity: there hasn't been a real need to go all-in with Symfony since Packages is a fairly small application. However, I recognize that Symfony is a much more stable platform than Nice.

I'm definitely open to considering a migration.

I'll close this, but please feel free to comment or raise a new issue if you have any questions. Thanks!
